spring:
  application:
    name: Verification Application
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: onboarding-verification-consumer

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

app:
  kafka:
    topic:
      applicant-created: applicant-updated-topic
      applicant-updated: applicant-updated-topic
      applicant-verified: applicant-verified-topic