spring:
  application:
    name: Onboarding Application
  output:
    ansi:
      enabled: detect
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/database}
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: onboarding-application-consumer

opentracing:
  jaeger:
    http-sender:
      url: ${JAEGER_URL:http://localhost:14268/api/traces}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

app:
  kafka:
    topic:
      applicant-created: applicant-updated-topic
      applicant-updated: applicant-updated-topic
      applicant-verified: applicant-verified-topic