spring:
  application:
    name: Onboarding Application
  datasource:
    url: jdbc:h2:mem:onboarding-db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: onboarding-application-consumer

app:
  kafka:
    topic:
      applicant-created: applicant-updated-topic
      applicant-updated: applicant-updated-topic